In [1]:
%%bash
pip install seaborn --user


In [9]:
#General Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import sklearn

from sklearn.ensemble import ExtraTreesClassifier 
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelBinarizer

#Autoenconder Functions
from keras.layers import Input, Dense, Dropout, BatchNormalization
from keras.models import Model
from sklearn.model_selection import train_test_split

#Nueral Network Functions
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Data Preprocessing

In [3]:
#List of Missing Values
missing_values = ["?", "NaN",]
#Import Data
Heartdata = pd.read_csv("processed.cleveland.data.txt", delimiter=",", header = None, na_values = missing_values)
Heartdata.head()

0    1    2      3      4    5    6      7    8    9    10   11   12  13
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   2
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   1
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   0

In [4]:
#Rename Data to fit algorithm
XData = Heartdata
XData.dtypes
#Data Visualization
col = XData.select_dtypes("number").columns
col
XData[col]

0    1    2      3      4    5    6      7    8    9    10   11   12  \
0    63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   
1    67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   
2    67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   
3    37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   
4    41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   
5    56.0  1.0  2.0  120.0  236.0  0.0  0.0  178.0  0.0  0.8  1.0  0.0  3.0   
6    62.0  0.0  4.0  140.0  268.0  0.0  2.0  160.0  0.0  3.6  3.0  2.0  3.0   
7    57.0  0.0  4.0  120.0  354.0  0.0  0.0  163.0  1.0  0.6  1.0  0.0  3.0   
8    63.0  1.0  4.0  130.0  254.0  0.0  2.0  147.0  0.0  1.4  2.0  1.0  7.0   
9    53.0  1.0  4.0  140.0  203.0  1.0  2.0  155.0  1.0  3.1  3.0  0.0  7.0   
10   57.0  1.0  4.0  140.0  192.0  0.0  0.0  148.0  0.0  0.4  2.0  0.0  6.0   
11   56.0  0.0  2.0  140.0  294.0  0.0  2.0  153.0  0.0  1.3  2.0  0.0  3.0   
12   56.0  1.0  3.0  130.0  256.0  1.0  2.0  142.0  1.0  0.6  2.0  1.0  6.0   
13   44.0  1.0  2.0  120.0  263.0  0.0  0.0  173.0  0.0  0.0  1.0  0.0  7.0   
14   52.0  1.0  3.0  172.0  199.0  1.0  0.0  162.0  0.0  0.5  1.0  0.0  7.0   
15   57.0  1.0  3.0  150.0  168.0  0.0  0.0  174.0  0.0  1.6  1.0  0.0  3.0   
16   48.0  1.0  2.0  110.0  229.0  0.0  0.0  168.0  0.0  1.0  3.0  0.0  7.0   
17   54.0  1.0  4.0  140.0  239.0  0.0  0.0  160.0  0.0  1.2  1.0  0.0  3.0   
18   48.0  0.0  3.0  130.0  275.0  0.0  0.0  139.0  0.0  0.2  1.0  0.0  3.0   
19   49.0  1.0  2.0  130.0  266.0  0.0  0.0  171.0  0.0  0.6  1.0  0.0  3.0   
20   64.0  1.0  1.0  110.0  211.0  0.0  2.0  144.0  1.0  1.8  2.0  0.0  3.0   
21   58.0  0.0  1.0  150.0  283.0  1.0  2.0  162.0  0.0  1.0  1.0  0.0  3.0   
22   58.0  1.0  2.0  120.0  284.0  0.0  2.0  160.0  0.0  1.8  2.0  0.0  3.0   
23   58.0  1.0  3.0  132.0  224.0  0.0  2.0  173.0  0.0  3.2  1.0  2.0  7.0   
24   60.0  1.0  4.0  130.0  206.0  0.0  2.0  132.0  1.0  2.4  2.0  2.0  7.0   
25   50.0  0.0  3.0  120.0  219.0  0.0  0.0  158.0  0.0  1.6  2.0  0.0  3.0   
26   58.0  0.0  3.0  120.0  340.0  0.0  0.0  172.0  0.0  0.0  1.0  0.0  3.0   
27   66.0  0.0  1.0  150.0  226.0  0.0  0.0  114.0  0.0  2.6  3.0  0.0  3.0   
28   43.0  1.0  4.0  150.0  247.0  0.0  0.0  171.0  0.0  1.5  1.0  0.0  3.0   
29   40.0  1.0  4.0  110.0  167.0  0.0  2.0  114.0  1.0  2.0  2.0  0.0  7.0   
..    ...  ...  ...    ...    ...  ...  ...    ...  ...  ...  ...  ...  ...   
273  71.0  0.0  4.0  112.0  149.0  0.0  0.0  125.0  0.0  1.6  2.0  0.0  3.0   
274  59.0  1.0  1.0  134.0  204.0  0.0  0.0  162.0  0.0  0.8  1.0  2.0  3.0   
275  64.0  1.0  1.0  170.0  227.0  0.0  2.0  155.0  0.0  0.6  2.0  0.0  7.0   
276  66.0  0.0  3.0  146.0  278.0  0.0  2.0  152.0  0.0  0.0  2.0  1.0  3.0   
277  39.0  0.0  3.0  138.0  220.0  0.0  0.0  152.0  0.0  0.0  2.0  0.0  3.0   
278  57.0  1.0  2.0  154.0  232.0  0.0  2.0  164.0  0.0  0.0  1.0  1.0  3.0   
279  58.0  0.0  4.0  130.0  197.0  0.0  0.0  131.0  0.0  0.6  2.0  0.0  3.0   
280  57.0  1.0  4.0  110.0  335.0  0.0  0.0  143.0  1.0  3.0  2.0  1.0  7.0   
281  47.0  1.0  3.0  130.0  253.0  0.0  0.0  179.0  0.0  0.0  1.0  0.0  3.0   
282  55.0  0.0  4.0  128.0  205.0  0.0  1.0  130.0  1.0  2.0  2.0  1.0  7.0   
283  35.0  1.0  2.0  122.0  192.0  0.0  0.0  174.0  0.0  0.0  1.0  0.0  3.0   
284  61.0  1.0  4.0  148.0  203.0  0.0  0.0  161.0  0.0  0.0  1.0  1.0  7.0   
285  58.0  1.0  4.0  114.0  318.0  0.0  1.0  140.0  0.0  4.4  3.0  3.0  6.0   
286  58.0  0.0  4.0  170.0  225.0  1.0  2.0  146.0  1.0  2.8  2.0  2.0  6.0   
287  58.0  1.0  2.0  125.0  220.0  0.0  0.0  144.0  0.0  0.4  2.0  NaN  7.0   
288  56.0  1.0  2.0  130.0  221.0  0.0  2.0  163.0  0.0  0.0  1.0  0.0  7.0   
289  56.0  1.0  2.0  120.0  240.0  0.0  0.0  169.0  0.0  0.0  3.0  0.0  3.0   
290  67.0  1.0  3.0  152.0  212.0  0.0  2.0  150.0  0.0  0.8  2.0  0.0  7.0   
291  55.0  0.0  2.0  132.0  342.0  0.0  0.0  166.0  0.0  

In [5]:
#Check for Missing Values
XData.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    4
12    2
13    0
dtype: int64

In [6]:
#Data Info
XData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
0     303 non-null float64
1     303 non-null float64
2     303 non-null float64
3     303 non-null float64
4     303 non-null float64
5     303 non-null float64
6     303 non-null float64
7     303 non-null float64
8     303 non-null float64
9     303 non-null float64
10    303 non-null float64
11    299 non-null float64
12    301 non-null float64
13    303 non-null int64
dtypes: float64(13), int64(1)
memory usage: 33.2 KB


In [8]:
#Remove Missing Values
XClean = XData.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
XClean

0    1    2      3      4    5    6      7    8    9    10   11   12  \
0    63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   
1    67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   
2    67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   
3    37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   
4    41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   
5    56.0  1.0  2.0  120.0  236.0  0.0  0.0  178.0  0.0  0.8  1.0  0.0  3.0   
6    62.0  0.0  4.0  140.0  268.0  0.0  2.0  160.0  0.0  3.6  3.0  2.0  3.0   
7    57.0  0.0  4.0  120.0  354.0  0.0  0.0  163.0  1.0  0.6  1.0  0.0  3.0   
8    63.0  1.0  4.0  130.0  254.0  0.0  2.0  147.0  0.0  1.4  2.0  1.0  7.0   
9    53.0  1.0  4.0  140.0  203.0  1.0  2.0  155.0  1.0  3.1  3.0  0.0  7.0   
10   57.0  1.0  4.0  140.0  192.0  0.0  0.0  148.0  0.0  0.4  2.0  0.0  6.0   
11   56.0  0.0  2.0  140.0  294.0  0.0  2.0  153.0  0.0  1.3  2.0  0.0  3.0   
12   56.0  1.0  3.0  130.0  256.0  1.0  2.0  142.0  1.0  0.6  2.0  1.0  6.0   
13   44.0  1.0  2.0  120.0  263.0  0.0  0.0  173.0  0.0  0.0  1.0  0.0  7.0   
14   52.0  1.0  3.0  172.0  199.0  1.0  0.0  162.0  0.0  0.5  1.0  0.0  7.0   
15   57.0  1.0  3.0  150.0  168.0  0.0  0.0  174.0  0.0  1.6  1.0  0.0  3.0   
16   48.0  1.0  2.0  110.0  229.0  0.0  0.0  168.0  0.0  1.0  3.0  0.0  7.0   
17   54.0  1.0  4.0  140.0  239.0  0.0  0.0  160.0  0.0  1.2  1.0  0.0  3.0   
18   48.0  0.0  3.0  130.0  275.0  0.0  0.0  139.0  0.0  0.2  1.0  0.0  3.0   
19   49.0  1.0  2.0  130.0  266.0  0.0  0.0  171.0  0.0  0.6  1.0  0.0  3.0   
20   64.0  1.0  1.0  110.0  211.0  0.0  2.0  144.0  1.0  1.8  2.0  0.0  3.0   
21   58.0  0.0  1.0  150.0  283.0  1.0  2.0  162.0  0.0  1.0  1.0  0.0  3.0   
22   58.0  1.0  2.0  120.0  284.0  0.0  2.0  160.0  0.0  1.8  2.0  0.0  3.0   
23   58.0  1.0  3.0  132.0  224.0  0.0  2.0  173.0  0.0  3.2  1.0  2.0  7.0   
24   60.0  1.0  4.0  130.0  206.0  0.0  2.0  132.0  1.0  2.4  2.0  2.0  7.0   
25   50.0  0.0  3.0  120.0  219.0  0.0  0.0  158.0  0.0  1.6  2.0  0.0  3.0   
26   58.0  0.0  3.0  120.0  340.0  0.0  0.0  172.0  0.0  0.0  1.0  0.0  3.0   
27   66.0  0.0  1.0  150.0  226.0  0.0  0.0  114.0  0.0  2.6  3.0  0.0  3.0   
28   43.0  1.0  4.0  150.0  247.0  0.0  0.0  171.0  0.0  1.5  1.0  0.0  3.0   
29   40.0  1.0  4.0  110.0  167.0  0.0  2.0  114.0  1.0  2.0  2.0  0.0  7.0   
..    ...  ...  ...    ...    ...  ...  ...    ...  ...  ...  ...  ...  ...   
271  66.0  1.0  4.0  160.0  228.0  0.0  2.0  138.0  0.0  2.3  1.0  0.0  6.0   
272  46.0  1.0  4.0  140.0  311.0  0.0  0.0  120.0  1.0  1.8  2.0  2.0  7.0   
273  71.0  0.0  4.0  112.0  149.0  0.0  0.0  125.0  0.0  1.6  2.0  0.0  3.0   
274  59.0  1.0  1.0  134.0  204.0  0.0  0.0  162.0  0.0  0.8  1.0  2.0  3.0   
275  64.0  1.0  1.0  170.0  227.0  0.0  2.0  155.0  0.0  0.6  2.0  0.0  7.0   
276  66.0  0.0  3.0  146.0  278.0  0.0  2.0  152.0  0.0  0.0  2.0  1.0  3.0   
277  39.0  0.0  3.0  138.0  220.0  0.0  0.0  152.0  0.0  0.0  2.0  0.0  3.0   
278  57.0  1.0  2.0  154.0  232.0  0.0  2.0  164.0  0.0  0.0  1.0  1.0  3.0   
279  58.0  0.0  4.0  130.0  197.0  0.0  0.0  131.0  0.0  0.6  2.0  0.0  3.0   
280  57.0  1.0  4.0  110.0  335.0  0.0  0.0  143.0  1.0  3.0  2.0  1.0  7.0   
281  47.0  1.0  3.0  130.0  253.0  0.0  0.0  179.0  0.0  0.0  1.0  0.0  3.0   
282  55.0  0.0  4.0  128.0  205.0  0.0  1.0  130.0  1.0  2.0  2.0  1.0  7.0   
283  35.0  1.0  2.0  122.0  192.0  0.0  0.0  174.0  0.0  0.0  1.0  0.0  3.0   
284  61.0  1.0  4.0  148.0  203.0  0.0  0.0  161.0  0.0  0.0  1.0  1.0  7.0   
285  58.0  1.0  4.0  114.0  318.0  0.0  1.0  140.0  0.0  4.4  3.0  3.0  6.0   
286  58.0  0.0  4.0  170.0  225.0  1.0  2.0  146.0  1.0  2.8  2.0  2.0  6.0   
288  56.0  1.0  2.0  130.0  221.0  0.0  2.0  163.0  0.0  0.0  1.0  0.0  7.0   
289  56.0  1.0  2.0  120.0  240.0  0.0  0.0  169.0  0.0  0.0  3.0  0.0  3.0   
290  67.0  1.0  3.0  152.0  212.0  0.0  2.0  150.0  0.0  

In [10]:
#Separate into X and Y components for data processing
Y = XClean[13]
X = XClean.drop(columns=[13])
print (X)

#Change output values to matrix of 0 & 1
lb = LabelBinarizer()
Y = lb.fit_transform(Y)
Y

       0    1    2      3      4    5    6      7    8    9    10   11   12
0    63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0
1    67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0
2    67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0
3    37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0
4    41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0
5    56.0  1.0  2.0  120.0  236.0  0.0  0.0  178.0  0.0  0.8  1.0  0.0  3.0
6    62.0  0.0  4.0  140.0  268.0  0.0  2.0  160.0  0.0  3.6  3.0  2.0  3.0
7    57.0  0.0  4.0  120.0  354.0  0.0  0.0  163.0  1.0  0.6  1.0  0.0  3.0
8    63.0  1.0  4.0  130.0  254.0  0.0  2.0  147.0  0.0  1.4  2.0  1.0  7.0
9    53.0  1.0  4.0  140.0  203.0  1.0  2.0  155.0  1.0  3.1  3.0  0.0  7.0
10   57.0  1.0  4.0  140.0  192.0  0.0  0.0  148.0  0.0  0.4  2.0  0.0  6.0
11   56.0  0.0  2.0  140.0  294.0  0.0  2.0  153.0  0.0  1.3  2.0  0.0  3.0
12   56.0  1

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       ...,
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]])

# AUTOENCODER

In [11]:
#Split Data into Training and Testing (Change for experiments)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.02, random_state=0)

def simpleAE(X,Y,encodersize, activationH, activationout):
    #create input layer
    input_layer = Input(shape=(X.shape[1],))
    #create encoder layer
    encoder_layer = Dense(encodersize, activation=activationH)(input_layer)
    #create decoder layer 
    decoder_layer = Dense(X.shape[1],activation = activationout)(encoder_layer)
    
    #create autoencoder and encoder models
    Autoencoder = Model(input_layer, decoder_layer)
    Encoder = Model(input_layer, encoder_layer)
    
    Autoencoder.compile(optimizer='adam', loss = 'mean_squared_error')
    
    
    Autoencoder.fit(X_train, X_train,
                   epochs = 50,
                   batch_size= 30,
                   shuffle=True,
                   verbose=1,
                   validation_data=(X_test, X_test))
    return Autoencoder, Encoder


In [14]:
#Call Autoencoder Function
(AE, E) = simpleAE(X,Y,6,'relu','relu')

Train on 291 samples, validate on 6 samples
Epoch 1/50
291/291 [==============================] - 0s 471us/step - loss: 7384.5650 - val_loss: 6569.0996
Epoch 2/50
291/291 [==============================] - 0s 27us/step - loss: 7155.9914 - val_loss: 6374.7495
Epoch 3/50
291/291 [==============================] - 0s 27us/step - loss: 6959.7964 - val_loss: 6211.3013
Epoch 4/50
291/291 [==============================] - 0s 24us/step - loss: 6793.7644 - val_loss: 6075.2632
Epoch 5/50
291/291 [==============================] - 0s 36us/step - loss: 6657.1811 - val_loss: 5961.1167
Epoch 6/50
291/291 [==============================] - 0s 36us/step - loss: 6539.7323 - val_loss: 5865.9478
Epoch 7/50
291/291 [==============================] - 0s 27us/step - loss: 6443.1450 - val_loss: 5784.1050
Epoch 8/50
291/291 [==============================] - 0s 43us/step - loss: 6359.7991 - val_loss: 5713.0117
Epoch 9/50
291/291 [==============================] - 0s 31us/step - loss: 6286.9742 - val_loss: 56

In [15]:
#Save the Learned features to use in the NN
learnedfeatures = E.predict(X_train)
ValidationFeatures = E.predict(X_test)
print(learnedfeatures)

[[  0.        10.570663   0.       193.92264    0.         0.      ]
 [  0.        30.261555   0.       282.24246    0.         0.      ]
 [  0.         6.058041   0.       215.97417    0.         0.      ]
 ...
 [  0.        19.793922   0.       243.24944    0.         0.      ]
 [  0.         0.         0.       209.08293    0.         0.      ]
 [  0.         0.         0.       196.38934    0.         0.      ]]


# Neural Network

In [16]:

NN = MLPClassifier(solver='sgd',alpha=1e-6, hidden_layer_sizes=(28,2),learning_rate ='adaptive', random_state=1)
NN.fit(learnedfeatures,Y_train)
NNPredicted = NN.predict(ValidationFeatures)
print(NNPredicted, Y_test)
NNAccuracy = accuracy_score(Y_test,NNPredicted)*100
print(NNAccuracy)

[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]] [[1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]]
66.66666666666666


c:\python36\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
